### PR TITLE
AlterTests AlterCollectionMigration doesn't have MigrationAttribute which let's the RunnerTests fail

### LINKED ISSUE #13: AlterCollectionMigration doesn't have MigrationAttribute which let's the RunnerTests fail
I'll send a PR soon

### PR DESCRIPTION
**Pull request by danielmarbach**
Closes #13

### CODE REVIEW

**Comment by rogersillito** [comment]
I'm guessing that the intention was for AlterTests to be atomic in relation to those contained in RunnerTests?  Assuming I'm right, would it be better to assign a higher number and profile to the migration attribute to fix this, so it wouldn't interfere with any tests added in future? e.g:

    [Migration(1000000, "for-AlterTests-only")]

Either way your fix works for me - hopefully it will get accepted soon.

**Comment by danielmarbach** [comment]
I think this project is no longer maintained. You can use my fork if you want.

**Comment by rogersillito** [comment]
OK - thanks, I created my own fork to fix another issue before seeing your reply.

**Comment by dportzline83** [comment]
This issue is fixed by 7c420c7568eaa65074a16d32cc63d974ab49a17a

**Pull request closed without merging**
